[overlay]
color=0xAF9D6A8B

[account_management.separator]
color=0xff0000

[achievement_diary.entry.border]
color=0xff9933
# opacity=150

[achievement_diary.progress.background]
color=0x9D6A76
# opacity=150

[deposit_lock.border.inner]
color=0x000000

[deposit_lock.border.outer]
color=0xffffff

[deposit_lock.locked]
color=0x00f0f3

[deposit_lock.unlocked]
color=0xf356ac

[deposit_lock.hovered.locked]
color=0xf0ac5e

[deposit_lock.hovered.unlocked]
color=0xacacac

[deposit_box.inventory.border.inner]
color=0x00ff00

[deposit_box.inventory.border.outer]
color=0xffff00

[deposit_box.inventory.locked]
color=0x00ff00

[bank.inventory.locked]
color=0x00ff00

[bank.inventory.rune_pouch.border.inner]
color=0x643A4B
# opacity=0

[bank.inventory.rune_pouch.border.outer]
color=0x9D6A76
# opacity=0

[bank.menu.border.inner]
color=0x643A4B
# opacity=0

[bank.menu.border.outer]
color=0x9D6A76
# opacity=0

[bank.menu.border.outer.fillers]
opacity=255

[bank.menu.border.inner.fillers]
opacity=255

[bank.popup.border.inner]
color=0x643A4B
# opacity=0

[bank.popup.border.outer]
color=0x9D6A76
# opacity=0

[bank.separator]
color=0x4d3736

[bonds_pouch.border.inner]
color=0x643A4B
# opacity=0

[bonds_pouch.border.outer]
color=0x9D6A76
# opacity=0

[bounty_hunter.overlay.background]
color=0xAF9D6A8B
# opacity=150

[bounty_hunter.overlay.border.inner]
color=0x643A4B

[bounty_hunter.overlay.border.outer]
color=0x9D6A76

[channel_tab.separator]
color=0xff0000

[chatbox.separator]
color=0xff0000
# opacity=200

[choose_spell.background]
color=0x000000
# opacity=0

[choose_spell.border.inner]
color=0x3C222C
# opacity=0

[choose_spell.border.outer]
color=0x9D6A76
# opacity=0

[clan_chat.border.inner]
color=0x9D6A76

[clan_chat.border.outer]
color=0x9D6A76

[colosseum.info.background]
color=0x000000
# opacity=200

[colosseum.info.border.inner]
color=0x3C222C
# opacity=0

[colosseum.info.border.outer]
color=0x9D6A76
# opacity=0

[colosseum.modifiers.border]
color=0x643A4B
# opacity=0

[colosseum.modifiers.selected]
color=0x9D6A76
# opacity=0

[colosseum.tab.border]
color=0x9D6A76
# opacity=0

[colosseum.wave.background]
color=0x000000
# opacity=200

[colosseum.wave.border.inner]
color=0x3C222C
# opacity=0

[colosseum.wave.border.outer]
color=0x9D6A76
# opacity=0

[collection_log.border]
color=0xff0000

[combat_achievements.progress.border.inner]
color=0x643A4B
# opacity=0

[combat_achievements.progress.border.outer]
color=0x9D6A76
# opacity=0

[combat_achievements.tasks.menu.border.inner]
color=0x9D6A76
# opacity=0

[combat_achievements.tasks.menu.border.outer]
color=0x3C222C
# opacity=0

[combat_achievements.tasks.dropdown.border.inner]
color=0x9D6A76
# opacity=0

[combat_achievements.tasks.dropdown.border.outer]
color=0x3C222C
# opacity=0

[combat_achievements.rewards.body.border.inner]
color=0x9D6A76
# opacity=0

[combat_achievements.rewards.body.border.outer]
color=0x3C222C
# opacity=0

[combat_achievements.rewards.section.border.inner]
color=0x643A4B
# opacity=0

[combat_achievements.rewards.section.border.outer]
color=0x9D6A76
# opacity=0

[combat_achievements.boss.border.inner]
color=0x9D6A76
# opacity=0

[combat_achievements.boss.border.outer]
color=0x3C222C
# opacity=0

[combat_achievements.overview.border]
color=0x643A4B
# opacity=150

[costumes.border.inner]
color=0x643A4B
# opacity=0

[costumes.border.outer]
color=0x9D6A76
# opacity=0

[cox.overlay.background]
color=0xAF9D6A8B
# opacity=0

[cox.overlay.border.inner]
color=0x9D6A76
# opacity=0

[cox.overlay.border.outer]
color=0x3C222C
# opacity=0

[cox.party.border.inner]
color=0x643A4B
# opacity=0

[cox.party.border.outer]
color=0x9D6A76
# opacity=0

[cox.parties.border.inner]
color=0x643A4B
# opacity=0

[cox.parties.border.outer]
color=0x9D6A76
# opacity=0

[forestry_kit.body.background]
color=0x000000
# opacity=200

[forestry_kit.body.border.inner]
color=0x3C222C
# opacity=0

[forestry_kit.body.border.outer]
color=0x9D6A76
# opacity=0

[forestry_kit.info.background]
color=0x000000
# opacity=200

[forestry_kit.info.border.inner]
color=0x3C222C
# opacity=0

[forestry_kit.info.border.outer]
color=0x9D6A76
# opacity=0

[forestry_shop.body.background]
color=0x000000
# opacity=200

[forestry_shop.body.border.inner]
color=0x3C222C
# opacity=0

[forestry_shop.body.border.outer]
color=0x9D6A76
# opacity=0

[forestry_shop.dropdown.border.inner]
color=0x9D6A76
# opacity=0

[forestry_shop.dropdown.border.outer]
color=0x3C222C
# opacity=0

[forestry_shop.info.background]
color=0x000000
# opacity=200

[forestry_shop.info.border.inner]
color=0x3C222C
# opacity=0

[forestry_shop.info.border.outer]
color=0x9D6A76
# opacity=0

[forestry_shop.menu.border.inner]
color=0x643A4B
# opacity=0

[forestry_shop.menu.border.outer]
color=0x9D6A76
# opacity=0

[forestry_shop.reward.unselected]
color=0xffffff

[forestry_shop.reward.selected]
color=0xff0000

[forestry_shop.reward.hovered]
color=0x00ff00
[friends_chat.border.inner]
color=0x9D6A76
# opacity=0

[friends_chat.border.outer]
color=0x3C222C
# opacity=0

[friends_chat.setup.border.inner]
color=0x9D6A76
# opacity=0

[friends_chat.setup.border.outer]
color=0x3C222C
# opacity=0

[friends_chat.header.border.inner]
color=0x9D6A76
# opacity=0

[friends_chat.header.border.outer]
color=0x3C222C
# opacity=0

[friends_list.header.border.inner]
color=0x9D6A76
# opacity=0

[friends_list.header.border.outer]
color=0x3C222C
# opacity=0

[ge.offer.border.inner]
color=0x643A4B
# opacity=0

[ge.offer.border.outer]
color=0x9D6A76
# opacity=0

[ge.slot.border.inner]
color=0x643A4B
# opacity=0

[ge.slot.border.outer]
color=0x9D6A76
# opacity=0

[grouping_tab.border.inner]
color=0xff981f
# opacity=150

[grouping_tab.border.outer]
color=0x3C222C
# opacity=0

[grouping_tab.dropdown.border.inner]
color=0x9D6A76
# opacity=150

[grouping_tab.dropdown.border.outer]
color=0x3C222C
# opacity=0

[ignore_list.header.border.inner]
color=0x9D6A76
# opacity=0

[ignore_list.header.border.outer]
color=0x3C222C
# opacity=0

[item_search.background]
color=0x9D6A76
# opacity=200

[item_search.border.inner]
color=0x643A4B
# opacity=150

[item_search.border.outer]
color=0x9D6A76
# opacity=0

[jewellery_box.border.inner]
color=0x643A4B
# opacity=0

[jewellery_box.border.outer]
color=0x9D6A76
# opacity=0

[lectern.border.inner]
color=0x643A4B
# opacity=0

[lectern.border.outer]
color=0x9D6A76
# opacity=0

[kept_on_death.border.inner]
color=0x3C222C
# opacity=0

[kept_on_death.border.outer]
color=0x9D6A76
# opacity=0

[looting_bag.border.inner]
color=0x9D6A76
# opacity=0

[looting_bag.border.outer]
color=0x3C222C
# opacity=0

[lms.kda.background]
color=0xAF9D6A8B
# opacity=100

[lms.kda.border.inner]
color=0x9D6A76
# opacity=0

[lms.kda.border.outer]
color=0x3C222C
# opacity=0

[lms.settings.border.inner]
color=0x9D6A76
# opacity=0

[lms.settings.border.outer]
color=0x3C222C
# opacity=0

[lms.shop.border.inner]
color=0x9D6A76
# opacity=0

[lms.shop.border.outer]
color=0x3C222C
# opacity=0

[lms.shop.separator]
color=0x5d5848
# opacity=0

# [lms.shop.separator.accent]
# color=0
# opacity=0

[make_all.background]
color=0xD3B5B8
# opacity=0

[make_all.quantity]
color=0xD3B5B8
# opacity=0

[other_clan.border.inner]
color=0x643A4B
# opacity=0

[other_clan.border.outer]
color=0x9D6A76
# opacity=0

[pet_house.border.inner]
color=0x643A4B
# opacity=150

[pet_house.border.outer]
color=0x9D6A76
# opacity=0

[poh.build_room.border]
color=0x643A4B
# opacity=0

[portal_nexus.border]
color=0x643A4B
# opacity=0

[pvp_arena.duel_options.separator]
color=0x643A4B
# opacity=100

[pvp_arena.confirm_options.separator]
color=0x5d5848
# opacity=100

# [pvp_arena.confirm_options.separator.accent]
# color=0
# opacity=100

[pvp_arena.recruitment.border.inner]
color=0x9D6A76
# opacity=0

[pvp_arena.recruitment.border.outer]
color=0x3C222C
# opacity=0

[pvp_arena.supplies.separator]
color=0x5d5848

[pvp_arena.supplies.stats.border.inner]
color=0x9D6A76
# opacity=0

[pvp_arena.supplies.stats.border.outer]
color=0x3C222C
# opacity=0

[pvp_arena.supplies.kit.equipment.border.inner]
color=0x9D6A76
# opacity=0

[pvp_arena.supplies.kit.equipment.border.outer]
color=0x3C222C
# opacity=0

[pvp_arena.supplies.kit.list.border.inner]
color=0x9D6A76
# opacity=0

[pvp_arena.supplies.kit.list.border.outer]
color=0x3C222C
# opacity=0

[pvp_arena.supplies.kit.inventory.border.inner]
color=0x9D6A76
# opacity=0

[pvp_arena.supplies.kit.inventory.border.outer]
color=0x3C222C
# opacity=0

[pvp_arena.supplies.kit.menu.border.inner]
color=0x9D6A76
# opacity=0

[pvp_arena.supplies.kit.menu.border.outer]
color=0x3C222C
# opacity=0

[pvp_arena.supplies.kit.dropdown.border.inner]
color=0x9D6A76
# opacity=0

[pvp_arena.supplies.kit.dropdown.border.outer]
color=0x3C222C
# opacity=0

[quest_list.background]
color=0x000000
# opacity=212

[quest_tab.separator]
color=0xff0000

[report.button.hover]
color=0xff0000

[rune_pouch.border.inner]
color=0x643A4B
# opacity=100

[rune_pouch.border.outer]
color=0x9D6A76
# opacity=100

[settings_tab.dropdown.border.inner]
color=0x9D6A76
# opacity=0

[settings_tab.dropdown.border.outer]
color=0x3C222C
# opacity=0

[settings_tab.menu.border.inner]
color=0x9D6A76
# opacity=0

[settings_tab.menu.border.outer]
color=0x3C222C
# opacity=0

[settings_tab.separator]
color=0xff0000

[settings.body.border.inner]
color=0x643A4B
# opacity=0

[settings.body.border.outer]
color=0x9D6A76
# opacity=0

[settings.menu.border.inner]
color=0x643A4B
# opacity=0

[settings.menu.border.outer]
color=0x9D6A76
# opacity=0

[settings.sidebar.border.inner]
color=0x643A4B
# opacity=0

[settings.sidebar.border.outer]
color=0x9D6A76
# opacity=0

[skill_guide.body.border.inner]
color=0x643A4B
# opacity=0

[skill_guide.body.border.outer]
color=0x9D6A76
# opacity=0

[skill_guide.tab.border]
color=0x643A4B
# opacity=0

[soul_wars.separator.bottom]
color=0x5d5848

# [soul_wars.separator.bottom.accent]
# color=0

[soul_wars.separator.top]
color=0x5d5848

# [soul_wars.separator.top.accent]
# color=0

[spell_tooltip.background]
color=0xAF9D6A8B
# opacity=40

[spell_tooltip.border.inner]
color=0x643A4B
# opacity=0

[spell_tooltip.border.outer]
color=0x9D6A76
# opacity=0

[toa.applicants.border.inner]
color=0x643A4B
# opacity=0

[toa.applicants.border.outer]
color=0x9D6A76
# opacity=0

[toa.invocations.border.inner]
color=0x643A4B
# opacity=0

[toa.invocations.border.outer]
color=0x9D6A76
# opacity=0

[toa.members.border.inner]
color=0x643A4B
# opacity=0

[toa.members.border.outer]
color=0x9D6A76
# opacity=0

[toa.parties.border.inner]
color=0x643A4B
# opacity=0

[toa.parties.border.outer]
color=0x9D6A76
# opacity=0

[toa.summary.border.inner]
color=0x643A4B
# opacity=0

[toa.summary.border.outer]
color=0x9D6A76
# opacity=0

[toa.separator.bottom]
color=0x5d5848

# [toa.separator.bottom.accent]
# color=0

[toa.separator.top]
color=0x5d5848

# [toa.separator.top.accent]
# color=0

[tob.applicants.border.inner]
color=0x643A4B
# opacity=0

[tob.applicants.border.outer]
color=0x9D6A76
# opacity=0

[tob.parties.border.inner]
color=0x643A4B
# opacity=0

[tob.parties.border.outer]
color=0x9D6A76
# opacity=0

[tob.party.border.inner]
color=0x643A4B
# opacity=0

[tob.party.border.outer]
color=0x9D6A76
# opacity=0

[tob.party.header.border.inner]
color=0x643A4B
# opacity=0

[tob.party.header.border.outer]
color=0x9D6A76
# opacity=0

[world_map.key.border.inner]
color=0x9D6A76
# opacity=0

[world_map.key.border.outer]
color=0x3C222C
# opacity=0

[world_map.dropdown.border.inner]
color=0x9D6A76
# opacity=0

[world_map.dropdown.border.outer]
color=0x3C222C
# opacity=0

[world_map.location_menu.border.inner]
color=0x9D6A76
# opacity=0

[world_map.location_menu.border.outer]
color=0x3C222C
# opacity=0

[world_map.search.border.inner]
color=0x9D6A76
# opacity=0

[world_map.search.border.outer]
color=0x3C222C
# opacity=0

[world_switcher.background]
color=0x000000

[world_switcher.border.bottom]
color=0x9D6A76
# opacity=50

[world_switcher.border.top]
color=0x9D6A76
# opacity=50

[xp_tracker.border.inner]
color=0x9D6A76
# opacity=0

[xp_tracker.border.outer]
color=0x3C222C
# opacity=0
