# This is a basic workflow to help you get started with Actions

name: Add Pack

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      pr:
        description: 'PR to run against'     
        required: true
        default: ''
      sha:
        description: 'SHA to checkout'     
        required: true
        default: ''
      ref:
        description: 'Name of pack to push'     
        required: true
        default: ''

run-name: ${{ inputs.pr }}-${{ inputs.sha }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Checkout pack
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
          path: pack

      - name: Download the latest vanilla sprites
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          repo: 'melkypie/sprite-exporter'
          file: '.*-sprites\.zip'
          regex: true
          target: "./"
      - name: Extract latest vanilla sprites
        run: unzip -jq *-sprites.zip -d sprites/

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run unneccessary file check on the pack
        run: |
          ./gradlew test -DspriteFolder="sprites" -DpackFolder="pack" --tests "melky.resourcepacks.ResourcePacksPluginTest.checkUnneededFiles" --rerun-tasks
